version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/html/mv-unisolve-fe
file_exists_behavior: OVERWRITE
hooks:
    BeforeInstall:
        - location: scripts/app_stop.sh
          timeout: 300
          runas: ubuntu
    AfterInstall:
        - location: scripts/app_start.sh
          timeout: 300
          runas: ubuntu
permissions:
    - object: /var/www/html/mv-unisolve-fe

      owner: ubuntu
      group: ubuntu
      type:
          - directory
          - file
