export const allStatus = ["COMPLETED", "INPROGRESS", "INCOMPLETE"];
export const allDistricts = [
    "ARIYALUR",
    "CHENGALPATTU",
    "CHENNAI",
    "COIMBATORE",
    "CUDDALORE",
    "DHARMAPURI",
    "DINDIGUL",
    "ERODE",
    "KALLAKURICHI",
    "KANCHEEPURAM",
    "KANNIYAKUMARI",
    "KARUR",
    "KRISHNAGIRI",
    "MADURAI",
    "MAYILADUTHURAI",
    "NAGAPATTINAM",
    "NAMAKKAL",
    "PERAMBALUR",
    "PUDUKKOTTAI",
    "RAMANATHAPURAM",
    "RANIPET",
    "SALEM",
    "SIVAGANGAI",
    "TENKASI",
    "THANJAVUR",
    "THE NILGIRIS",
    "THENI",
    "THIRUVANNAMALAI",
    "THOOTHUKKUDI",
    "TIRUCHIRAPPALLI",
    "TIRUNELVELI",
    "TIRUPATHUR",
    "TIRUPPUR",
    "TIRUVALLUR",
    "TIRUVANNAMALAI",
    "TIRUVARUR",
    "VELLORE",
    "VILLUPURAM",
    "VIRUDHUNAGAR",
    "ALL"
];

export const allTypes = { "tr": "Registration", "tpre": "Pre Survey", "tc": "Course Completion", "tpost": "Post Survey" };
